const C = {
    W: 800, H: 450,
    TILE: 32,
    SCALE: 2,
    GRAVITY: 0.35,
    MAX_FALL: 11,
    WALK_SPEED: 2.2,
    RUN_SPEED: 3.8,
    JUMP_VEL: -9.5,
    ENEMY_SPEED: 1.5,
    MUSHROOM_SPEED: 2.0,
    // Tile types
    T_AIR: 0,
    T_GROUND: 1,
    T_BRICK: 2,
    T_QBLOCK: 3,
    T_QUSED: 4,
    T_SOLID: 5,
    T_PIPE_TL: 6, T_PIPE_TR: 7,
    T_PIPE_BL: 8, T_PIPE_BR: 9,
    T_COIN: 10,
    T_STAIR: 11,
    T_CASTLE: 12,
    T_INVISIBLE: 13,
    // Game states
    STATE_MENU: 'menu',
    STATE_LEVEL_SELECT: 'levelSelect',
    STATE_GAME: 'game',
    STATE_GAME_OVER: 'gameOver',
    STATE_LEVEL_CLEAR: 'levelClear',
    // Colors
    SKY: '#5C94FC',
    GROUND_TOP: '#E56820',
    GROUND_FILL: '#AB4611',
    BRICK_TOP: '#C84B11',
    BRICK_FILL: '#AB4611',
    QBLOCK: '#FAC000',
    QBLOCK_DARK: '#D49000',
    PIPE: '#24B048',
    PIPE_DARK: '#167030',
    SOLID: '#AAAAAA',
    STAIR: '#C87830',
};
